name: tesseroids2
dependencies:
    - python=3.5
    - pip
    - numpy
    - numba
    - matplotlib
    - basemap
    - pytest
    - pytest-cov
    - coverage
    - pep8
    - sphinx
    - pip:
        - sphinx_rtd_theme
